Web/TrendyMemes.Web/Areas/Posts/ViewModels/Comments/CommentCreateInputModel.cs
namespace TrendyMemes.Web.Areas.Posts.ViewModels.Comments
{
    using System.ComponentModel.DataAnnotations;

    using TrendyMemes.Common.Attributes;

    public class CommentCreateInputModel
    {
        [Required]
        [MinLengthWithCustomMessage(3)]
        [MaxLength(1000)]
        public string Content { get; set; }

        [Required]
        public int PostId { get; set; }
    }
}

Web/TrendyMemes.Web/Areas/Posts/ViewModels/Comments/CommentListViewModel.cs
namespace TrendyMemes.Web.Areas.Posts.ViewModels.Comments
{
    using TrendyMemes.Data.Models;
    using TrendyMemes.Services.Mapping;

    public class CommentListViewModel : IMapFrom<Comment>
    {
        public string AuthorId { get; set; }

        public string AuthorUsername { get; set; }

        public string Content { get; set; }
    }
}

Web/TrendyMemes.Web/Areas/Posts/ViewModels/Posts/PostCreateInputModel.cs
namespace TrendyMemes.Web.Areas.Posts.ViewModels.Posts
{
    using System.ComponentModel.DataAnnotations;

    using Microsoft.AspNetCore.Http;
    using TrendyMemes.Common.Attributes;

    public class PostCreateInputModel
    {
        [Required]
        [MinLengthWithCustomMessage(3)]
        [MaxLengthWithCustomMessage(20)]
        public string Title { get; set; }

        [Required]
        public IFormFile Image { get; set; }

        [Required]
        [MinLengthWithCustomMessage(2)]
        [MaxLengthWithCustomMessage(200)]
        public string Tags { get; set; }
    }
}

Web/TrendyMemes.Web/Areas/Posts/ViewModels/Posts/PostDetailsViewModel.cs
namespace TrendyMemes.Web.Areas.Posts.ViewModels.Posts
{
    using System.Collections.Generic;

    using TrendyMemes.Data.Models;
    using TrendyMemes.Services.Mapping;
    using TrendyMemes.Web.Areas.Posts.ViewModels.Comments;

    public class PostDetailsViewModel : PostInListViewModel, IMapFrom<Post>
    {
        public PostDetailsViewModel()
            : base()
        {
            this.Comments = new List<CommentListViewModel>();
        }

        public IEnumerable<CommentListViewModel> Comments { get; set; }
    }
}

Web/TrendyMemes.Web/Areas/Posts/ViewModels/Posts/PostEditInputModel.cs
namespace TrendyMemes.Web.Areas.Posts.ViewModels.Posts
{
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;

    using AutoMapper;

    using TrendyMemes.Common.Attributes;
    using TrendyMemes.Data.Models;
    using TrendyMemes.Services.Mapping;

    public class PostEditInputModel : IMapFrom<Post>, IHaveCustomMappings
    {
        [Required]
        [MinLengthWithCustomMessage(3)]
        [MaxLengthWithCustomMessage(20)]
        public string Title { get; set; }

        [Required]
        [MinLengthWithCustomMessage(2)]
        [MaxLengthWithCustomMessage(200)]
        public string Tags { get; set; }

        public string ImageSrc { get; set; }

        public void CreateMappings(IProfileExpression configuration)
        {
            configuration.CreateMap<Post, PostEditInputModel>()
                .ForMember(pe => pe.Tags, opt => opt.MapFrom(p => string.Join(' ', p.PostTags.Select(t => t.Tag.Name))))
                .ForMember(pe => pe.ImageSrc, opt => opt.MapFrom(p => Path.Combine(@"\images", $"{p.ImageId}.{p.Image.Extension}")));
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/ViewModels/Posts/PostInListViewModel.cs
namespace TrendyMemes.Web.Areas.Posts.ViewModels.Posts
{
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;

    using AutoMapper;

    using TrendyMemes.Data.Models;
    using TrendyMemes.Services.Mapping;
    using TrendyMemes.Web.Areas.Tags.ViewModels;

    public class PostInListViewModel : IMapFrom<Post>, IHaveCustomMappings
    {
        public PostInListViewModel()
        {
            this.Tags = new List<TagInListViewModel>();
        }

        public int Id { get; set; }

        public string Title { get; set; }

        public string AuthorId { get; set; }

        public string AuthorUsername { get; set; }

        public string ImagePath { get; set; }

        public int Rating { get; set; }

        public IEnumerable<TagInListViewModel> Tags { get; set; }

        public void CreateMappings(IProfileExpression configuration)
        {
            configuration
            .CreateMap<Post, PostInListViewModel>()
            .Include<Post, PostDetailsViewModel>()
            .ForMember(vm => vm.ImagePath, opt => opt.MapFrom(p => Path.Combine(@"images", $"{p.ImageId}.{p.Image.Extension}")))
            .ForMember(vm => vm.Tags, opt => opt.MapFrom(p => p.PostTags.Select(pt => pt.Tag)));
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/ViewModels/Posts/PostsListViewModel.cs
namespace TrendyMemes.Web.Areas.Posts.ViewModels.Posts
{
    using System.Collections.Generic;

    public class PostsListViewModel
    {
        public PostsListViewModel()
        {
            this.Posts = new List<PostInListViewModel>();
        }

        public IEnumerable<PostInListViewModel> Posts { get; set; }
    }
}

Web/TrendyMemes.Web/Areas/Posts/ViewModels/Tags/TagInListViewModel.cs
namespace TrendyMemes.Web.Areas.Tags.ViewModels
{
    using AutoMapper;
    using TrendyMemes.Data.Models;
    using TrendyMemes.Services.Mapping;

    public class TagInListViewModel : IMapFrom<Tag>, IMapFrom<PostTag>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public void CreateMappings(IProfileExpression configuration)
        {
            configuration
                .CreateMap<PostTag, TagInListViewModel>()
                .ForMember(vm => vm.Id, opt => opt.MapFrom(pt => pt.TagId))
                .ForMember(vm => vm.Name, opt => opt.MapFrom(pt => pt.Tag.Name));
        }
    }
}

Web/TrendyMemes.Web/Areas/Identity/Controllers/UsersController.cs
namespace TrendyMemes.Web.Areas.Identity.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using TrendyMemes.Common;
    using TrendyMemes.Web.Areas.Identity.Services;
    using TrendyMemes.Web.Controllers;

    [Area(GlobalConstants.IdentityArea)]
    public class UsersController : BaseController
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public IActionResult Details(string id)
        {
            var user = this.usersService.GetProfileById(id);

            return this.View(user);
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/Controllers/CommentsController.cs
namespace TrendyMemes.Web.Areas.Posts.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using TrendyMemes.Common;
    using TrendyMemes.Data.Models;
    using TrendyMemes.Web.Areas.Posts.Services;
    using TrendyMemes.Web.Areas.Posts.ViewModels.Comments;
    using TrendyMemes.Web.Controllers;

    [Area(GlobalConstants.PostsArea)]
    public class CommentsController : BaseController
    {
        private readonly ICommentsService commentsService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentsController(ICommentsService commentsService, UserManager<ApplicationUser> userManager)
        {
            this.commentsService = commentsService;
            this.userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CommentCreateInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                var author = await this.userManager.GetUserAsync(this.User);
                await this.commentsService.CreateAsync(input, author.Id);
            }

            return this.RedirectToAction(nameof(PostsController.Details), ControllerHelpers.GetControllerName(nameof(PostsController)), new
            {
                area = GlobalConstants.PostsArea,
                id = input.PostId,
            });
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(CommentCreateInputModel input)
        {
            return this.View();
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Delete()
        {
            return this.View();
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/Controllers/PostsController.cs
namespace TrendyMemes.Web.Areas.Posts.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using TrendyMemes.Common;
    using TrendyMemes.Data.Models;
    using TrendyMemes.Web.Areas.Posts.Services;
    using TrendyMemes.Web.Areas.Posts.ViewModels.Posts;
    using TrendyMemes.Web.Controllers;

    [Area(GlobalConstants.PostsArea)]
    public class PostsController : BaseController
    {
        private const string PostsListView = "List";

        private readonly IPostsService postsService;
        private readonly UserManager<ApplicationUser> userManager;

        public PostsController(IPostsService postsService, UserManager<ApplicationUser> userManager)
        {
            this.postsService = postsService;
            this.userManager = userManager;
        }

        [HttpGet(nameof(Details))]
        public IActionResult Details(int id)
        {
            var post = this.postsService.GetById<PostDetailsViewModel>(id);

            return this.View(post);
        }

        [HttpGet(nameof(Trendy))]
        public IActionResult Trendy()
        {
            var posts = this.postsService.GetTopPercent<PostInListViewModel>(0, GlobalConstants.TopPostsPercentageInTrendyCategory);
            var viewModel = new PostsListViewModel { Posts = posts };

            return this.View(PostsListView, viewModel);
        }

        [HttpGet(nameof(Rising))]
        public IActionResult Rising()
        {
            var posts = this.postsService.GetTopPercent<PostInListViewModel>(GlobalConstants.TopPostsPercentageInTrendyCategory, GlobalConstants.TopPostsPercentageInRisingCategory);
            var viewModel = new PostsListViewModel { Posts = posts };

            return this.View(PostsListView, viewModel);
        }

        [HttpGet(nameof(New))]
        public IActionResult New()
        {
            var posts = this.postsService.GetTopPercent<PostInListViewModel>(GlobalConstants.PostsPercentageInNewCategory, 100);
            var viewModel = new PostsListViewModel { Posts = posts };

            return this.View(PostsListView, viewModel);
        }

        [HttpGet("ByTag")]
        public IActionResult ByTagId(int id)
        {
            var posts = this.postsService.GetByTagId<PostInListViewModel>(id);
            var viewModel = new PostsListViewModel { Posts = posts };

            return this.View(PostsListView, viewModel);
        }

        [HttpGet("ByUser")]
        public IActionResult ByUserId(string id)
        {
            var posts = this.postsService.GetByUserId<PostInListViewModel>(id);
            var viewModel = new PostsListViewModel { Posts = posts };

            return this.View(PostsListView, viewModel);
        }

        [HttpGet(nameof(Create))]
        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost(nameof(Create))]
        [Authorize]
        public async Task<IActionResult> Create(PostCreateInputModel input)
        {
            if (this.ModelState.IsValid == false)
            {
                return this.View(input);
            }

            var author = await this.userManager.GetUserAsync(this.User);
            var tags = input.Tags.Split(' ', System.StringSplitOptions.RemoveEmptyEntries).Distinct();
            var newPostId = await this.postsService.CreateAsync(input, author.Id, tags);

            return this.RedirectToAction(nameof(this.Details), new { id = newPostId });
        }

        [HttpGet(nameof(Edit) + "/{id}")]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Edit(int id)
        {
            var post = this.postsService.GetById<PostEditInputModel>(id);

            return this.View(post);
        }

        [HttpPost(nameof(Edit) + "/{id}")]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Edit(int id, PostEditInputModel input)
        {
            if (this.ModelState.IsValid == false)
            {
                return this.View(input);
            }

            var tags = input.Tags.Split(' ', System.StringSplitOptions.RemoveEmptyEntries).Distinct();
            await this.postsService.UpdateAsync(input, id, tags);

            return this.RedirectToAction(nameof(this.Details), new { id });
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> Delete(int id)
        {
            await this.postsService.DeleteAsync(id);

            return this.RedirectToAction(nameof(HomeController.Index), ControllerHelpers.GetControllerName(nameof(HomeController)), new { area = GlobalConstants.HomeArea });
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/Controllers/VotesController.cs
namespace TrendyMemes.Web.Areas.Posts.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using TrendyMemes.Common;
    using TrendyMemes.Data.Models;
    using TrendyMemes.Web.Areas.Posts.Services;

    [Area(GlobalConstants.PostsArea)]
    [ApiController]
    public class VotesController : ControllerBase
    {
        private readonly IVotesService votesService;
        private readonly UserManager<ApplicationUser> userManager;

        public VotesController(IVotesService votesService, UserManager<ApplicationUser> userManager)
        {
            this.votesService = votesService;
            this.userManager = userManager;
        }

        [HttpGet(nameof(Upvote))]
        [Authorize]
        public async Task<int> Upvote(int id)
        {
            var rating = await this.VoteOnPost(id, 1);

            return rating;
        }

        [HttpGet(nameof(Downvote))]
        [Authorize]
        public async Task<int> Downvote(int id)
        {
            var rating = await this.VoteOnPost(id, -1);

            return rating;
        }

        [NonAction]
        private async Task<int> VoteOnPost(int id, int value)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var rating = await this.votesService.VoteOnPostAsync(id, user.Id, value);

            return rating;
        }
    }
}

Web/TrendyMemes.Web/Controllers/TagsController.cs
namespace TrendyMemes.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class TagsController : BaseController
    {
        public IActionResult AllByTag(int id)
        {
            return this.View();
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/Views/Posts/All.cshtml
@model TrendyMemes.Web.Areas.Posts.Viewmodels.PostsListViewModel;
<div class="container">
    <div class="row">
        @foreach (var post in Model.Posts)
        {
            <article class="card col-md-12 m-2">
                <div class="card-body">
                    <h2 class="card-title text-center">
                        <a asp-action="Details" asp-route-id="@post.Id">
                            @post.Title
                        </a>
                    </h2>
                    <img class="card-img-top" src="https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MXx8aHVtYW58ZW58MHx8MHw%3D&ixlib=rb-1.2.1&w=1000&q=80" alt="Card image cap">
                    <p class="card-text">
                        @foreach (var tag in post.Tags)
                        {
                            <a asp-controller="Tags" asp-action="Details" asp-route-id="@tag.Id">
                                @tag.Name&nbsp;
                            </a>
                        }
                    </p>
                    <p class="card-text">
                        @post.Score
                    </p>
                </div>
            </article>
        }
    </div>
</div>

Web/TrendyMemes.Web/Areas/Posts/Views/Posts/Create.cshtml
@model TrendyMemes.Web.Areas.Posts.ViewModels.Posts.PostCreateInputModel

<div class="container card card-body">
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Create" method="post" enctype="multipart/form-data" class="col-md-8">
                <div class="row card-title">
                    <h2>Create a new post</h2>
                </div>
                <div class="row">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control w-100" placeholder="Enter the title here" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="row">
                    <label asp-for="Tags"></label>
                    <input asp-for="Tags" class="form-control" placeholder="Enter the tags here, separated by a space" />
                    <span asp-validation-for="Tags" class="text-danger"></span>
                </div>
                <div class="row">
                    <label asp-for="Image">Image</label>
                    <input id="image-upload" asp-for="Image" accept="image/jpeg, image/png" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <br />
                <div class="row">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <img id="image-preview" class="w-100 card-img">
        </div>
    </div>
</div>

Web/TrendyMemes.Web/Areas/Posts/Views/Posts/Details.cshtml
@using TrendyMemes.Web.Areas.Posts.ViewModels.Posts
@using TrendyMemes.Web.Areas.Posts.ViewModels.Comments
@model PostDetailsViewModel

<div class="container">
    <div class="row">
        <div class="col-md-12 row-md-12">
            <h2 class="card-title text-center">
                @Model.Title
            </h2>
            <img class="card-img-top" src="@Model.ImagePath">
            <p class="card-text">
                <span> Author:
                    <a asp-area="Identity" asp-controller="Users" asp-action="Details" asp-route-id="@Model.AuthorId">
                        <span> @Model.AuthorUsername </span>
                    </a>
                </span>
                <span> Tags:
                    @foreach (var tag in Model.Tags)
                    {
                        <a asp-action="ByTagId" asp-route-id="@tag.Id"> @tag.Name </a>
                    }
                </span>
            </p>
            <div class="row">
                @await Html.PartialAsync("_VotingPanel", Model)
            </div>
        </div>
    </div>
    @if (User.IsInRole("Administrator"))
    {
        <div class="row">
            @await Html.PartialAsync("_AdminPanel", Model)
        </div>
    }
    <div class="row">
        @if (User.Identity.IsAuthenticated)
        {
            @await Html.PartialAsync("_CommentCreateForm", new CommentCreateInputModel{ PostId=Model.Id })
        }
        @foreach (var comment in Model.Comments)
        {
            @await Html.PartialAsync("_CommentsList", comment)
        }
    </div>
</div>

Web/TrendyMemes.Web/Areas/Posts/Views/Posts/Edit.cshtml
@using TrendyMemes.Web.Areas.Posts.ViewModels.Posts
@model PostEditInputModel

<div class="container card card-body">
    <div class="row">
        <div class="col-md-6">
            <form asp-action="Edit" method="post" enctype="multipart/form-data" class="col-md-8">
                <div class="row card-title">
                    <h2>Edit post</h2>
                </div>
                <div class="row">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control w-100" placeholder="Enter the title here" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="row">
                    <label asp-for="Tags"></label>
                    <input asp-for="Tags" class="form-control" placeholder="Enter the tags here, separated by a space" />
                    <span asp-validation-for="Tags" class="text-danger"></span>
                </div>
                <br />
                <div class="row">
                    <button class="btn btn-primary" type="submit">Edit</button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <img class="w-100 card-img" src="@Model.ImageSrc">
        </div>
    </div>
</div>

Web/TrendyMemes.Web/Areas/Posts/Views/Posts/List.cshtml
@model TrendyMemes.Web.Areas.Posts.ViewModels.Posts.PostsListViewModel;

<div class="container">
    <div class="row">
        @foreach (var post in Model.Posts)
        {
            @await Html.PartialAsync("_PostInList", post)
        }
    </div>
</div>

Web/TrendyMemes.Web/Areas/Posts/Views/Posts/_PostInList.cshtml
@model TrendyMemes.Web.Areas.Posts.ViewModels.Posts.PostInListViewModel;

<article class="card col-md-12 m-2 box-shadow">
    <div class="card-body">
        <h2 class="card-title text-center">
            <a asp-action="Details" asp-route-id="@Model.Id">
                @Model.Title
            </a>
        </h2>
        <a asp-action="Details" asp-route-id="@Model.Id">
            <img src="@Model.ImagePath" alt="Post image" class="card-img-top" />
        </a>
        <p class="card-text">
            <span> Author:
                <a asp-area="Identity" asp-controller="Users" asp-action="Details" asp-route-id="@Model.AuthorId">
                    <span> @Model.AuthorUsername </span>
                </a>
            </span>
            <span> Tags:
                @foreach (var tag in Model.Tags)
                {
                    <a asp-action="ByTagId" asp-route-id="@tag.Id">
                        @tag.Name
                    </a>
                }
            </span>
        </p>
        <div class="row">
            @await Html.PartialAsync("_VotingPanel", Model)
        </div>
    </div>
</article>