Web/TrendyMemes.Web/Areas/Identity/Controllers/UsersController.cs
namespace TrendyMemes.Web.Areas.Identity.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using TrendyMemes.Common;
    using TrendyMemes.Web.Areas.Identity.Services;
    using TrendyMemes.Web.Controllers;

    [Area(GlobalConstants.IdentityArea)]
    public class UsersController : BaseController
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }

        public IActionResult Details(string id)
        {
            var user = this.usersService.GetProfileById(id);

            return this.View(user);
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/Controllers/CommentsController.cs
namespace TrendyMemes.Web.Areas.Posts.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using TrendyMemes.Common;
    using TrendyMemes.Data.Models;
    using TrendyMemes.Web.Areas.Posts.Services;
    using TrendyMemes.Web.Areas.Posts.ViewModels.Comments;
    using TrendyMemes.Web.Controllers;

    [Area(GlobalConstants.PostsArea)]
    public class CommentsController : BaseController
    {
        private readonly ICommentsService commentsService;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentsController(ICommentsService commentsService, UserManager<ApplicationUser> userManager)
        {
            this.commentsService = commentsService;
            this.userManager = userManager;
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CommentCreateInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                var author = await this.userManager.GetUserAsync(this.User);
                await this.commentsService.CreateAsync(input, author.Id);
            }

            return this.RedirectToAction(nameof(PostsController.Details), ControllerHelpers.GetControllerName(nameof(PostsController)), new
            {
                area = GlobalConstants.PostsArea,
                id = input.PostId,
            });
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(CommentCreateInputModel input)
        {
            return this.View();
        }

        [HttpGet]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public IActionResult Delete()
        {
            return this.View();
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/Controllers/VotesController.cs
namespace TrendyMemes.Web.Areas.Posts.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using TrendyMemes.Common;
    using TrendyMemes.Data.Models;
    using TrendyMemes.Web.Areas.Posts.Services;

    [Area(GlobalConstants.PostsArea)]
    [ApiController]
    public class VotesController : ControllerBase
    {
        private readonly IVotesService votesService;
        private readonly UserManager<ApplicationUser> userManager;

        public VotesController(IVotesService votesService, UserManager<ApplicationUser> userManager)
        {
            this.votesService = votesService;
            this.userManager = userManager;
        }

        [HttpGet(nameof(Upvote))]
        [Authorize]
        public async Task<int> Upvote(int id)
        {
            var rating = await this.VoteOnPost(id, 1);

            return rating;
        }

        [HttpGet(nameof(Downvote))]
        [Authorize]
        public async Task<int> Downvote(int id)
        {
            var rating = await this.VoteOnPost(id, -1);

            return rating;
        }

        [NonAction]
        private async Task<int> VoteOnPost(int id, int value)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var rating = await this.votesService.VoteOnPostAsync(id, user.Id, value);

            return rating;
        }
    }
}

Web/TrendyMemes.Web/Areas/Posts/Views/Shared/_AdminPanel.cshtml
@using TrendyMemes.Web.Areas.Posts.ViewModels.Posts
@model PostDetailsViewModel

<div class="card card-body border border-danger m-2 p-0 flex-row">
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-secondary col m-2">Edit</a>
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-secondary col m-2">Delete</a>
</div>

Web/TrendyMemes.Web/Areas/Posts/Views/Shared/_CommentCreateForm.cshtml
@model TrendyMemes.Web.Areas.Posts.ViewModels.Comments.CommentCreateInputModel

<form asp-controller="Comments" asp-action="Create" method="post" class="w-100 card card-body m-2">
    <textarea asp-for="Content" placeholder="Type your comment here" rows="3" class="w-100 border-0"></textarea>
    <input type="hidden" name="PostId" value="@Model.PostId" />
    <span asp-validation-for="Content" class="text-danger"></span>
    <button type="submit" class="btn btn-primary col-md-2">Post comment</button>
</form>

Web/TrendyMemes.Web/Areas/Posts/Views/Shared/_CommentsList.cshtml
@model TrendyMemes.Web.Areas.Posts.ViewModels.Comments.CommentListViewModel

<div class="w-100 card card-body m-2">
    <a asp-area="Identity" asp-controller="Users" asp-action="Details" asp-route-id="@Model.AuthorId">
        <h6 class="h6"> @Model.AuthorUsername </h6>
    </a>
    <p>@Model.Content</p>
    @* @if (User.Identity.IsAuthenticated)
        {
        <a class="btn btn-secondary">Reply</a>
        } *@
    @* @if (UserId)
        {
        <a class="btn btn-secondary">Edit</a>
        <a class="btn btn-secondary">Delete</a>
        } *@
</div>

Web/TrendyMemes.Web/Areas/Posts/Views/Shared/_VotingPanel.cshtml
<a asp-controller="Votes" asp-action="Upvote" asp-route-id="@Model.Id" class="offset-md-3 col-md-2 btn btn-success upvote">
    Upvote
</a>
<h3 class="col-md-2 text-center rating card-text @(Model.Rating>0?"text-success":"text-danger")">
    @Model.Rating
</h3>
<a asp-controller="Votes" asp-action="Downvote" asp-route-id="@Model.Id" class="col-md-2 btn btn-danger downvote">
    Downvote
</a>